### ISSUE TITLE
!h5ls 'my_results.h5ad' dose not work

### ISSUE THREAD

**Issue by yingsun-ucsd** [scverse/anndata-tutorials#12]
I am very new to AnnData and trying to learn by following the tutorials at https://anndata-tutorials.readthedocs.io/en/latest/getting-started.html. Everything works until step [15]. I got the following error message:
________________________
>>> adata.write('my_results.h5ad', compression="gzip")
>>> !h5ls 'my_results.h5ad'
  File "<stdin>", line 1
    !h5ls 'my_results.h5ad'
    ^
SyntaxError: invalid syntax
>>> 
________________________

Any ideas or suggestions? Thanks.

**Comment by falexwolf** [comment]
Executing with a prepended `!` sends the command to the shell. This is a shell command, not a Python statement.

**Comment by yingsun-ucsd** [comment]
Sorry, my fault. Thanks.
